name = "Zeus Enhanced"
prefix = "zen"
author = "ZEN Team"
mainprefix = "x"

[files]
include = [
    "mod.cpp",
    "logo_zen_ca.paa",
    "logo_zen_small_ca.paa",
    "LICENSE",
    "AUTHORS.txt",
    "README.md",
    "meta.cpp"
]

[asc]
enabled = true
exclude = [
    ".inc.sqf",
    "/dev/"
]
